#ifndef __HCUBE_NeuralNetworkPanel__
#define __HCUBE_NeuralNetworkPanel__

/**
@file
Subclass of NeuralNetworkPanelTemplate, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "HCUBE_GUITemplate.h"

#include "HCUBE_Defines.h"

namespace HCUBE
{

    /** Implementing NeuralNetworkPanelTemplate */
    class NeuralNetworkPanel : public NeuralNetworkPanelTemplate
    {
        //wxBitmap outputBitmap;

    public:
        /** Constructor */
        NeuralNetworkPanel( wxWindow* parent, int id, wxPoint pos, wxSize size, int style );

        void setTarget(shared_ptr<NEAT::GeneticIndividual> individual);

        void setReadOnly(bool value);

        bool isReadOnly();

        //void createNetworkImage(shared_ptr<const NEAT::GeneticIndividual> individual);

        //void paint(wxPaintEvent& event);

        //void handleMouseClick(wxMouseEvent& event);

        //DECLARE_EVENT_TABLE()

    };

}

#endif // __HCUBE_NeuralNetworkPanel__
